version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: root:root
    network_mode: "host"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - ./.mount/config:/config
      - ./.mount/cache:/cache
      - /home/anpandu/Downloads/torrents:/media
      - /home/anpandu/Pictures/gallery-dl:/media-gdl
    devices:
      - /dev/dri:/dev/dri #optional
    restart: "unless-stopped"
    environment:
      - TZ=Asia/Jakarta
      - JELLYFIN_PublishedServerUrl=192.168.2.138 #optional

